"""Init

Revision ID: 60adcfb038a3
Revises: 
Create Date: 2023-05-14 16:07:06.276081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60adcfb038a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_table('users')
    # ### end Alembic commands ###
